//! Routes for endpoints not yet fully implemented.
//! All return HTTP 501 with a consistent error body.

use axum::Router;
use axum::routing::{delete, get, post, put};

use crate::app_state::AppState;
use crate::handlers::stub;

pub fn router() -> Router<AppState> {
    Router::new()
        // Assets (extended)
        .route("/api/assets/jobs", post(stub::not_implemented))
        .route("/api/assets/copy", put(stub::not_implemented))
        .route("/api/assets/metadata", put(stub::not_implemented))
        .route("/api/assets/metadata", delete(stub::not_implemented))
        .route("/api/assets/{id}/metadata", get(stub::not_implemented))
        .route("/api/assets/{id}/ocr", get(stub::not_implemented))
        .route("/api/assets/{id}/metadata", put(stub::not_implemented))
        .route("/api/assets/{id}/metadata/{key}", get(stub::not_implemented))
        .route("/api/assets/{id}/metadata/{key}", delete(stub::not_implemented))
        .route("/api/assets/{id}/edits", get(stub::not_implemented))
        .route("/api/assets/{id}/edits", put(stub::not_implemented))
        .route("/api/assets/{id}/edits", delete(stub::not_implemented))
        // Video stream (HLS)
        .route("/api/assets/{id}/video/stream/main.m3u8", get(stub::not_implemented))
        .route(
            "/api/assets/{id}/video/stream/{sessionId}/{variantIndex}/playlist.m3u8",
            get(stub::not_implemented),
        )
        .route(
            "/api/assets/{id}/video/stream/{sessionId}/{variantIndex}/{filename}",
            get(stub::not_implemented),
        )
        .route(
            "/api/assets/{id}/video/stream/{sessionId}",
            delete(stub::not_implemented),
        )
        // Duplicates
        .route("/api/duplicates", get(stub::not_implemented))
        .route("/api/duplicates", delete(stub::not_implemented))
        .route("/api/duplicates/{id}", delete(stub::not_implemented))
        .route("/api/duplicates/resolve", post(stub::not_implemented))
        // Download
        .route("/api/download/info", post(stub::not_implemented))
        .route("/api/download/archive", post(stub::not_implemented))
        // View
        .route("/api/view/folder/unique-paths", get(stub::not_implemented))
        .route("/api/view/folder", get(stub::not_implemented))
        // People & faces
        .route("/api/people", get(stub::not_implemented))
        .route("/api/people", post(stub::not_implemented))
        .route("/api/people", put(stub::not_implemented))
        .route("/api/people", delete(stub::not_implemented))
        .route("/api/people/{id}", get(stub::not_implemented))
        .route("/api/people/{id}", put(stub::not_implemented))
        .route("/api/people/{id}", axum::routing::patch(stub::not_implemented))
        .route("/api/people/{id}", delete(stub::not_implemented))
        .route("/api/people/{id}/statistics", get(stub::not_implemented))
        .route("/api/people/{id}/thumbnail", get(stub::not_implemented))
        .route("/api/people/{id}/reassign", put(stub::not_implemented))
        .route("/api/people/{id}/merge", post(stub::not_implemented))
        .route("/api/faces", post(stub::not_implemented))
        .route("/api/faces", get(stub::not_implemented))
        .route("/api/faces/{id}", put(stub::not_implemented))
        .route("/api/faces/{id}", delete(stub::not_implemented))
        // Partners
        .route("/api/partners", get(stub::not_implemented))
        .route("/api/partners", post(stub::not_implemented))
        .route("/api/partners/{id}", post(stub::not_implemented))
        .route("/api/partners/{id}", put(stub::not_implemented))
        .route("/api/partners/{id}", delete(stub::not_implemented))
        // Activities
        .route("/api/activities", get(stub::not_implemented))
        .route("/api/activities", post(stub::not_implemented))
        .route("/api/activities/statistics", get(stub::not_implemented))
        .route("/api/activities/{id}", delete(stub::not_implemented))
        // Memories (extended)
        .route("/api/memories", post(stub::not_implemented))
        .route("/api/memories/statistics", get(stub::not_implemented))
        .route("/api/memories/{id}", get(stub::not_implemented))
        .route("/api/memories/{id}", put(stub::not_implemented))
        .route("/api/memories/{id}", axum::routing::patch(stub::not_implemented))
        .route("/api/memories/{id}", delete(stub::not_implemented))
        .route("/api/memories/{id}/assets", put(stub::not_implemented))
        .route("/api/memories/{id}/assets", delete(stub::not_implemented))
        // Stacks
        .route("/api/stacks", get(stub::not_implemented))
        .route("/api/stacks", post(stub::not_implemented))
        .route("/api/stacks", delete(stub::not_implemented))
        .route("/api/stacks/{id}", get(stub::not_implemented))
        .route("/api/stacks/{id}", put(stub::not_implemented))
        .route("/api/stacks/{id}", axum::routing::patch(stub::not_implemented))
        .route("/api/stacks/{id}", delete(stub::not_implemented))
        .route("/api/stacks/{id}/assets/{assetId}", delete(stub::not_implemented))
        // Sync
        .route("/api/sync/stream", post(stub::not_implemented))
        .route("/api/sync/ack", get(stub::not_implemented))
        .route("/api/sync/ack", post(stub::not_implemented))
        .route("/api/sync/ack", delete(stub::not_implemented))
        // Map
        .route("/api/map/markers", get(stub::not_implemented))
        .route("/api/map/reverse-geocode", get(stub::not_implemented))
        // Libraries (admin)
        .route("/api/libraries", get(stub::not_implemented))
        .route("/api/libraries", post(stub::not_implemented))
        .route("/api/libraries/{id}", get(stub::not_implemented))
        .route("/api/libraries/{id}", put(stub::not_implemented))
        .route("/api/libraries/{id}", axum::routing::patch(stub::not_implemented))
        .route("/api/libraries/{id}", delete(stub::not_implemented))
        .route("/api/libraries/{id}/validate", post(stub::not_implemented))
        .route("/api/libraries/{id}/statistics", get(stub::not_implemented))
        .route("/api/libraries/{id}/scan", post(stub::not_implemented))
        // Workflows
        .route("/api/workflows", post(stub::not_implemented))
        .route("/api/workflows", get(stub::not_implemented))
        .route("/api/workflows/triggers", get(stub::not_implemented))
        .route("/api/workflows/{id}", get(stub::not_implemented))
        .route("/api/workflows/{id}/share", get(stub::not_implemented))
        .route("/api/workflows/{id}", put(stub::not_implemented))
        .route("/api/workflows/{id}", axum::routing::patch(stub::not_implemented))
        .route("/api/workflows/{id}", delete(stub::not_implemented))
        // Plugins
        .route("/api/plugins", get(stub::not_implemented))
        .route("/api/plugins/methods", get(stub::not_implemented))
        .route("/api/plugins/templates", get(stub::not_implemented))
        .route("/api/plugins/{id}", get(stub::not_implemented))
        // Notifications
        // Notifications (extended)
        .route("/api/notifications", put(stub::not_implemented))
        .route("/api/notifications", delete(stub::not_implemented))
        .route("/api/notifications/{id}", get(stub::not_implemented))
        .route("/api/notifications/{id}", put(stub::not_implemented))
        .route("/api/notifications/{id}", delete(stub::not_implemented))
        // Admin notifications
        .route("/api/admin/notifications", post(stub::not_implemented))
        .route("/api/admin/notifications/test-email", post(stub::not_implemented))
        .route("/api/admin/notifications/templates/{name}", post(stub::not_implemented))
        // System config (admin)
        .route("/api/system-config", get(stub::not_implemented))
        .route("/api/system-config/defaults", get(stub::not_implemented))
        .route("/api/system-config", put(stub::not_implemented))
        .route("/api/system-config/storage-template-options", get(stub::not_implemented))
        // System metadata (admin)
        .route("/api/system-metadata/reverse-geocoding-state", get(stub::not_implemented))
        .route("/api/system-metadata/version-check-state", get(stub::not_implemented))
        // Jobs & queues (admin)
        .route("/api/jobs", get(stub::not_implemented))
        .route("/api/jobs", post(stub::not_implemented))
        .route("/api/jobs/{name}", put(stub::not_implemented))
        .route("/api/queues", get(stub::not_implemented))
        .route("/api/queues/{name}", get(stub::not_implemented))
        .route("/api/queues/{name}", put(stub::not_implemented))
        .route("/api/queues/{name}/jobs", get(stub::not_implemented))
        .route("/api/queues/{name}/jobs", delete(stub::not_implemented))
        // Maintenance (admin)
        .route("/api/admin/maintenance/detect-install", get(stub::not_implemented))
        .route("/api/admin/maintenance", post(stub::not_implemented))
        // Integrity (admin)
        .route("/api/admin/integrity/summary", get(stub::not_implemented))
        .route("/api/admin/integrity/report", get(stub::not_implemented))
        .route("/api/admin/integrity/report/{id}/file", get(stub::not_implemented))
        .route("/api/admin/integrity/report/{id}", delete(stub::not_implemented))
        .route("/api/admin/integrity/report/{type}/csv", get(stub::not_implemented))
        // Database backups (admin)
        .route("/api/admin/database-backups", get(stub::not_implemented))
        .route("/api/admin/database-backups/{filename}", get(stub::not_implemented))
        .route("/api/admin/database-backups", delete(stub::not_implemented))
        .route("/api/admin/database-backups/upload", post(stub::not_implemented))
        // User admin
        .route("/api/admin/users", get(stub::not_implemented))
        .route("/api/admin/users", post(stub::not_implemented))
        .route("/api/admin/users/{id}", get(stub::not_implemented))
        .route("/api/admin/users/{id}", put(stub::not_implemented))
        .route("/api/admin/users/{id}", axum::routing::patch(stub::not_implemented))
        .route("/api/admin/users/{id}", delete(stub::not_implemented))
        .route("/api/admin/users/{id}/calendar-heatmap", get(stub::not_implemented))
        .route("/api/admin/users/{id}/sessions", get(stub::not_implemented))
        .route("/api/admin/users/{id}/statistics", get(stub::not_implemented))
        .route("/api/admin/users/{id}/preferences", get(stub::not_implemented))
        .route("/api/admin/users/{id}/preferences", put(stub::not_implemented))
        .route("/api/admin/users/{id}/preferences", axum::routing::patch(stub::not_implemented))
        .route("/api/admin/users/{id}/restore", post(stub::not_implemented))
}
